version: '3.1'

services:
  db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_PASSWORD: pswd
      POSTGRES_USER: user
      POSTGRES_DB: dbname
    volumes:
      - ./data:/var/lib/postgresql
    ports:
      - "5432:5432"

  adminer:
    image: adminer
    restart: always
    ports:
      - 8085:8080