version: '2'

services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: postgres
      POSTGRES_DB: parrotdb
    volumes:
      - ./data:/var/lib/postgresql
    ports:
      - "5432:5432"
    restart: always

  adminer:
    image: adminer
    ports:
      - 8085:8080