version: '3.1'

services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: postgres
      POSTGRES_DB: parrotdb
    volumes:
      - ./data:/var/lib/postgresql
    ports:
      - "5432:5432"

  adminer:
    image: adminer
    ports:
      - 8085:8080

  pgadmin:
    image: dpage/pgadmin4
    restart: always
    ports:
      - 8086:80
    environment:
      PGADMIN_DEFAULT_EMAIL: sahand@parrot
      PGADMIN_DEFAULT_PASSWORD: sahand


      